// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIIdB1RFBUkShvoR9ouWjpoyqkFk6YaEw',
    appId: '1:201048628809:web:e47d101794663cadcba998',
    messagingSenderId: '201048628809',
    projectId: 'portfoliomarin-4416b',
    authDomain: 'portfoliomarin-4416b.firebaseapp.com',
    storageBucket: 'portfoliomarin-4416b.appspot.com',
    measurementId: 'G-05YBPQ0PN5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy_U_2Y0d2piEVhM8yzUoTQQC_KOmpzyo',
    appId: '1:201048628809:android:30d02855f9978bfccba998',
    messagingSenderId: '201048628809',
    projectId: 'portfoliomarin-4416b',
    storageBucket: 'portfoliomarin-4416b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEjBTOkrcsHZny42bmIZfjI0h40ByJ1Yk',
    appId: '1:201048628809:ios:e7cb3d51f4e2e082cba998',
    messagingSenderId: '201048628809',
    projectId: 'portfoliomarin-4416b',
    storageBucket: 'portfoliomarin-4416b.appspot.com',
    iosBundleId: 'com.example.portfolioMarin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEjBTOkrcsHZny42bmIZfjI0h40ByJ1Yk',
    appId: '1:201048628809:ios:6d7a99ef981d4a15cba998',
    messagingSenderId: '201048628809',
    projectId: 'portfoliomarin-4416b',
    storageBucket: 'portfoliomarin-4416b.appspot.com',
    iosBundleId: 'com.example.portfolioMarin.RunnerTests',
  );
}
